name: Run experiment

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'dvc pipline'
        uses: actions/checkout@v1

      - uses: ./.github/actions/dvc-action
        env:
          dvc_file: train.dvc
          dvc_push: false
          dvc_endpoint: "https://c7ca2215.ngrok.io/api/data"
          github_token: ${{ secrets.GITHUB_TOKEN }}
