name: Run experiment

on: push

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: docker://davidgortega/dvc-action:latest
        env:
          dvc_file: train.dvc
          dvc_push: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
