name: Run experiment

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/dvc-action
        env:
          dvc_file: train.dvc
          artifacts_expiration: 1M
            
